### 本地开发环境

################## 框架参数配置 ###################

server:
  port: 80
  #servlet:
  #context-path: /SunYatSen
  tomcat:
    max-connections: 10000
    max-threads: 200
    min-spare-threads: 10


spring:
  resources:
    static-locations: classpath:/webapps/static/,file:${file.PathWindows}/static/,file:${file.PathLinux}/static/
  datasource:
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: admin123456!@#
    dynamic:
      primary: master
      ########### datasource ###########
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true
          url: jdbc:mysql://129.204.30.9:3306/SunYatSenAiAPI?useUnicode=true&characterEncoding=utf8&autoReconnect=true
          username: root
          password: ly123456
          druid:
            initialSize: 10
            maxActive: 30
            minIdle: 10
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 180000
            testWhileIdle: true
            validationQuery: select 1 from dual


### redis
redis:
  host: 129.204.30.9
  port: 6379
  password: ly123456
  database: 1

### mongodb
mongodb:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          host: 129.204.18.61
          port: 27017
          database: campus_brain
          username: chenjiayu
          password: chenjiayu
        my:
          host: 129.204.18.61
          port: 27017
          database: campus_brain
          username: chenjiayu
          password: chenjiayu

### mybatis
mybatis-plus:
  typeAliasesPackage: com.shizy.entity.*
  mapper-locations: classpath:mapper/*/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置 1:删除 0：未删除
#    logic-delete-value: 1
#    logic-not-delete-value: 0
    #自定义SQL注入器 逻辑删除SQL注入器
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 日志输出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




################## 项目自定义参数 ###################


### 文件存放的地址-绝对路径
file:
  PathWindows: d:/file
  PathLinux: /opt/file








